CREATE TABLE IF NOT EXISTS dogs (
    id                           SERIAL PRIMARY KEY,
    "animalID"                   TEXT UNIQUE NOT NULL,
    "animalName"                 TEXT,
    "animalStatus"               TEXT,
    "animalAdoptionFee"          TEXT,
    "animalPrimaryBreed"         TEXT,
    "animalSex"                  TEXT,
    "animalGeneralAge"           TEXT,
    "animalGeneralSizePotential" TEXT,
    "animalSizeCurrent"          TEXT,
    "animalSizeUOM"              TEXT,
    "animalColor"                TEXT,
    "animalDescriptionPlain"     TEXT,
    "animalThumbnailUrl"         TEXT,
    "animalPictures"             TEXT,
    "animalUrl"                  TEXT,
    "animalBirthdate"            TEXT,
    "animalOKWithKids"           TEXT,
    "animalOKWithDogs"           TEXT,
    "animalOKWithCats"           TEXT,
    "animalHousetrained"         TEXT,
    "animalAltered"              TEXT,
    "animalActivityLevel"        TEXT,
    "animalEnergyLevel"          TEXT,
    "animalLocation"             TEXT,
    "animalSpecialneeds"         TEXT,
    "animalSpecialneedsDescription" TEXT,
    "animalNeedsFoster"          TEXT,
    "animalOKForSeniors"         TEXT,
    "animalApartment"            TEXT,
    "animalPlayful"              TEXT,
    "animalAffectionate"         TEXT,
    "animalGentle"               TEXT,
    "animalTimid"                TEXT,
    "animalLap"                  TEXT,
    "animalIntelligent"          TEXT,
    "animalEagerToPlease"        TEXT,
    "animalGoofy"                TEXT,
    "animalIndependent"          TEXT,
    "animalProtective"           TEXT,
    "animalSkittish"             TEXT,
    "animalObedient"             TEXT,
    "animalFetches"              TEXT,
    "animalSwims"                TEXT,
    "animalPlaysToys"            TEXT,
    "animalGoodInCar"            TEXT,
    "animalCratetrained"         TEXT,
    "animalLeashtrained"         TEXT,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dog_status (
    dog_id     INT PRIMARY KEY REFERENCES dogs(id) ON DELETE CASCADE,
    adopted    BOOLEAN NOT NULL DEFAULT FALSE,
    adopted_at TIMESTAMPTZ,
    notes      TEXT
)